theme: jekyll-theme-cayman
title: "MinKhoy's Website"
description: "My own Writeup for Security Box solving, I have written some Writeup on Notion before (for some boxes on tryhackme), if you do want to take a look, here is the link - " [Notion Easy Box Tryhackme](https://www.notion.so/Box-easy-5032f503b5ce48e7a179d2d52c65a073)
